### ISSUE TITLE
Duda con SDK .Net

### ISSUE THREAD

**Issue by rodriguezclaudioa** [TodoPago/SDK-.NET#10]
Hola estoy usando este SDK, funciona correctamente, el único tema es que cuando se aprueba la operación   en el campo "CONCEPTO" de mi cuenta veo el id de la operación y no la descripción del producto ingresado en  "CSITPRODUCTDESCRIPTION".

Saludos

**Comment by drarko** [comment]
Estimado,
Esto es correcto, cuando se opera por SDK, en el portal el campo Concepto corresponde al parámetro OPERATIONID del SDK.

Saludos.
