### ISSUE TITLE
Link del ejemplo del formulario híbrido no funciona

### ISSUE THREAD

**Issue by smfiorillo** [TodoPago/SDK-.NET#11]
Hola,

Podrías indicar/subir el ejemplo del formulario híbrido? Estuve viendo en todo el repo y no lo encontré, y el link de la documentación tira  NOT FOUND.

Por otro lado, intenté armarlo el formulario tal cual lo especifican ahí, pero estoy obteniendo esta respuesta:

Object {field: "publicKey", error: "Ocurrio un error al listar los medios de pago, verifique que el publicKey sea valido"}

Debuggeandolo en forma local, encontré que en realidad al cargar los medios de pago, la respuesta que obtiene es:

" 2050 / Lo sentimos, el botón de pago ya no está disponible. Comunicate con tu vendedor."

Que luego lo encapsula en el mensaje de error mencionado más arriba. Cómo soluciono esto?
Desde ya gracias

**Comment by drarko** [comment]
Estimado, buenas tardes
Revisaremos los archivos de ejemplo.

Por favor, revise que en campo publicKey esta colocando el PublicRequestKey que devuelve el servicio SendAuthorizeRequest y que ademas, no haya pasado mas de 30 minutos de la llamada al servicio ya que ese es el tiempo de expiracion por default

Saludos

**Comment by smfiorillo** [comment]
Estoy trabajando en modo sandbox, usando la publicKey brindada en la documentación. Hasta este punto no hice ningun pago, solo cargué el aspx que contiene el form hibrido, con los campos a completar en el formulario para hacer el pago luego. Al intentar cargar los tipos de pago en el control correspondiente obtengo ese error. 

Lo que mencionás de SendAuthorizeRequest en qué momento debería hacerlo según la descripción que menciono arriba?

**Comment by solisarg** [comment]
Ok, veo que este hilo tiene un año, asi que traigo las novedades del 2018
El ejemplo esta outdated: https://github.com/TodoPago/SDK-PHP/blob/master/resources/form_hibrido-ejemplo/index.html

Notoriamente han cambiado el nombre de los js que se incluyen, ahora son
**Desarrollo**: https://developers.todopago.com.ar/resources/v2/TPBSAForm.min.js
**Produccion**: https://forms.todopago.com.ar/resources/v2/TPBSAForm.min.js

Los nombres de los campos han cambiado, quitandole el 'de', por ejemplo formaDePagoCbx ahora es formaPagoCbx, hay que agregar el combo medioPagoCbx, numeroTarjetaLbl, dia/mes/año pasa a ser combo y se llaman mesCbx, anioCbx, etc

En fin, si setearon el validationCollector vayan siguiendo los mensajes de error y van a ir podiendo renombrar o adivinar que campo falta

Suerte

**Comment by alejocba04** [comment]
Buenos dias, podrias mandar una version actualizada y funcionando del formulario hibrido?

**Comment by agus757** [comment]
> Buenos dias, podrias mandar una version actualizada y funcionando del formulario hibrido?

Lograste que funcione?

**Comment by curcio79** [comment]
@agus757 buenos dias, estas teniendo problemas para la implementacion? please crea un nuevo issue y lo seguimos. Saludos
