### ISSUE TITLE
Cuenta Invalida 

### ISSUE THREAD

**Issue by uricata77** [TodoPago/SDK-.NET#12]
Buenas tardes, 
estoy recibiendo el siguiente error: 
{"StatusCode":702,"StatusMessage":"Cuenta de vendedor invalida"}
Tanto con los código de producción como de prueba.. probé regenerarlos pero sigue el error.

**Comment by gshokida** [comment]
Buen día, podrías probar realizando una llamada a getCredentials con tus credenciales, y verificar si es el mismo merchant y apikey?

Saludos.

**Comment by uricata77** [comment]
Buenos días, con getCredentials devuelve las credenciales de pruebas. Estas funcionan OK. Las que figuran en la web como ambiente de producción, responden cuenta inválida. 
Gracias, por la rta. saludos.
