### ISSUE TITLE
CSBTIPADDRESS -> IPv6

### ISSUE THREAD

**Issue by RodrigoCalvo** [TodoPago/SDK-.NET#13]
Hola a todos!

Les comento que tenemos hecha la integracion con Todo Pago en algunos sitios de e-commerce y, en algunos casos, las IP de nuestros cliente resultan ser IPv6. Esto es algo que el campo CSBTIPADDRESS no soporta y nos devuelve el siguiente mensaje:

> _El formato del campo CSBTIPADDRESS es incorrecto (IPV4)_

Gracias! Saludos.

**Comment by drarko** [comment]
Estimado,
Se esta incorporando este feature en los proximos releases. Informaremos adecuadamente cuando se encuentre productivo. 
Gracias
