### ISSUE TITLE
Formulario de pago en la UI del ecommerce

### ISSUE THREAD

**Issue by RodrigoCalvo** [TodoPago/SDK-.NET#14]
Hola, muy buenos días!

Les comento que hemos desarrollado un formulario de pagos en el front end de nuestros ecommerces. El cual nos gustaría que "tome" las opciones de pago desde Todo Pago, se las presente al cliente y éste elija como quiere pagar. Al oprimir "pagar" la idea es enviar el resultado del form a Todo Pago para que procese el pago en cuestión.
En resumen sería "evitar" la redireccion al formulario de Todo Pago para hacerlo "on site" pero que Todo Pago continue siendo el procesador de pagos de la plataforma.

Aguardo sus comentarios; desde ya muchisimas gracias.
Saludos, Rodrigo Calvo

**Comment by drarko** [comment]
@RodrigoCalvo fijate la integración del Formulario Hibrido.
https://github.com/TodoPago/SDK-.NET#formulario-h%C3%ADbrido

Saludos

**Comment by RodrigoCalvo** [comment]
Excelente! voy a checkearlo.


Saludos y buen fin de semana.
