### ISSUE TITLE
Paquete NuGet para facilitar integracion y actualizaciones

### ISSUE THREAD

**Issue by jacargentina** [TodoPago/SDK-.NET#16]
Sería bueno contar con un paquete nuget de la libreria, para facilitar la integracion (referencias en los proyectos) y tambien futuras actualizaciones

Puedo aportar el desarrollo necesario en un PR.

**Comment by curcio79** [comment]
@jacargentina gracias por la info. Pronto vamos a comenzar la nueva version asi que podriamos verlo. Saludos
