### ISSUE TITLE
Error code : 99997 - Lo sentimos, en este momento la operación no puede ser realizada. Por favor intentá más tarde.

### ISSUE THREAD

**Issue by RodrigoCalvo** [TodoPago/SDK-.NET#18]
Hola, buenos días.

En algunas transacciones que procesamos con nuestra plataforma (según estimamos menos del 5%) vemos que a los compradores les da este error. 

Queremos saber a qué se debe ya que la descripción no nos permite darnos cuenta si es un problema de integración o del comprador en referencia a algún dato puntual de la compra.

Muchas gracias! un saludo.

**Comment by drarko** [comment]
Estimado,
El codigo en cuestion se trata de un rechazo del medio de pago. Puede pedirle al comprador que intente con otra tarjeta.
Saludos

**Comment by RodrigoCalvo** [comment]
Excelente! de mucha ayuda gracias.
