### ISSUE TITLE
URL de reedirección no contiene OPERATIONID

### ISSUE THREAD

**Issue by yvcabrera** [TodoPago/SDK-.NET#2]
Según la documentación en la url [https://github.com/TodoPago/SDK-.NET]. La reedirección a una de las url especificadas en  el servicio SendAurhorizationRequest, como resultado de un pago realizado, deben contener los campos [OPERATIONID y AnswerKey].

Ejemplo : http://susitio.com/paydtodopago/ok?Order=27398173292187&Answer=1111-2222-3333-4444-5555-6666-7777

He realizado un pago de pruebas y la reedirección no contiene el campo OPERATIONID.
Ejemplo : http://www.someurl.com/ok/?from=@&Answer=6b39e23d-3ade-32a2-e6dd-0c70c3313554

Saludos, Yandy

**Comment by damianwajser** [comment]
El order_id lo debes agregar vos al momento de realizar en sendauthorizerequest en la URL OK  o URL error.

Slds.

**Comment by yvcabrera** [comment]
Hoy lo estoy llamando de esta forma :
sendAuthorizeRequestParams.Add(URL_OK, "http://someurl.com/ok");

Entonces debería ser de esta forma :
sendAuthorizeRequestParams.Add(URL_OK, "http://someurl.com/ok?Order=123243243");

S, Yandy

**Comment by damianwajser** [comment]
Exactamente

**Comment by yvcabrera** [comment]
Gracias por la ayuda....

Saludos, Yandy
