### ISSUE TITLE
Status Code

### ISSUE THREAD

**Issue by yvcabrera** [TodoPago/SDK-.NET#3]
Me surge una duda : El status code de una transacción me llega en -1, no debería ser según los códigos de estado indicados.

![img](https://cloud.githubusercontent.com/assets/16673786/12299196/9ed9bd36-b9e3-11e5-80ba-1b10e573af56.jpg)

S, Yandy

**Comment by damianwajser** [comment]
No.
Esos códigos sirven para ver el estado de la transacción a partir del get status.
El resultcode -1 implica que el servicio se ejecutó correctamente.

**Comment by yvcabrera** [comment]
Te muestro imagen del resultado de un get status :

Si es resultcode, llega en -1

![msg](https://cloud.githubusercontent.com/assets/16673786/12300023/9a4aca04-b9e7-11e5-95e5-ba3943c6f1ec.jpg)

**Comment by damianwajser** [comment]
Los códigos de estado son solamente para operaciones especiales.
En el flujo normal el -1 es todo OK. Y para mensajes tenes el campo resultmessage.

**Comment by yvcabrera** [comment]
Cuales serian los posibles mensajes en resultmessage ?

Otro detalle : Si se llama al método sendGetStatus, con un getStatusOperationId inexistente, te genera un error, podria retornar null  o lo tenes contemplado de esa forma?

**Comment by damianwajser** [comment]
Los mensajes son de acuerdo al motivo de error y origen del error.
No lo podrías llamar con un transacción ID inexistente. ... el servicio respondería null.

**Comment by yvcabrera** [comment]
Una vez recibida la notificación de la transacción por la url acordada, es necesario llamar a "GetAuthorizeAnswer" o puedo directamente llamar a "GetStatus", para saber el estado  y detalles de la transacción.

**Comment by damianwajser** [comment]
Debes llamar al getauthorizerequest ya que con ese servicio informas a todo pago que volviste a tomar el control... por lo cual ahí cierra el ciclo transaccional.

**Comment by yvcabrera** [comment]
OK, gracias por la ayuda..
