### ISSUE TITLE
Cuotas

### ISSUE THREAD

**Issue by yvcabrera** [TodoPago/SDK-.NET#4]
Hola Damián. Te consulto es posible indicar la cantidad de coutas en las que se va a efectuar el pago, mediante parámetro, una vez que se levante el formulario de pago [No me refiero a poder eligir una en el formulario, sino que cuando se cargue, ya esté seleccionada la indicada anteriomente].

S, Yandy

**Comment by damianwajser** [comment]
Buenas Tardes, 
Lo que solicitas no es posible debido al modelo de negocio de TODO PAGO. 
Estas cuestiones podrías llegar a resolverlas con el sector comercial.
Saludos!

**Comment by yvcabrera** [comment]
Gracias...!!!!
