### ISSUE TITLE
Error en SendAuthorizeRequest

### ISSUE THREAD

**Issue by yvcabrera** [TodoPago/SDK-.NET#5]
Hola Damian buenas tardes. Estoy obteniendo esta respuesta como response de una petición de autorización de pago.

<resultcode>ERROR</resultcode>
        <resultmessage>Referencia a objeto no establecida como instancia de un objeto.</resultmessage>
        <urlrequest />
        <requestkey />
        <publicrequestkey />

**Comment by damianwajser** [comment]
En que momento te está sucediendo? Que versión de la sdk estas utilizando? Podrías enviarme la línea en donde te está fallando? 
Gracias.
slds.

**Comment by yvcabrera** [comment]
Damian he encontrado el error. La línea que produce el error es la siguiente :

var res = _connector.SendAuthorizeRequest(_sendAuthorizeRequestParams, _sendAuthorizeRequestPayload);

La causa es que estaba enviando credenciales de producción al endpoint de testing. Pero igual creo que en tal caso, la respuesta no deberia ser un error no controlado en la dll, sino un mensaje mas asequible para el usuario.
