### ISSUE TITLE
getByRangeDateTime

### ISSUE THREAD

**Issue by gfernandez87** [TodoPago/SDK-.NET#8]
Estimados estoy probando la librería en el entorno de pruebas, y cuando consulto el método getByRangeDateTime no me devuelve ninguna operación, pero si me las devuelve si ingreso al sitio developers (https://developers.todopago.com.ar/app/#cuentaResumen). Alguien a probado dicho metodo?.

Espero me puedan ayudar.
Saludos!

**Comment by guillermoluced** [comment]
Este issue se soluciono en el ultimo release.
Gracias.
