### ISSUE TITLE
Error cargando la cantidad de cuotas

### ISSUE THREAD

**Issue by yvcabrera** [TodoPago/SDK-.NET#9]
Hola buenas tardes. Cuando obtengo la url del SendAuthorizeRequest, posterior a insertar una tarjeta, no carga las cuotas, el sitio de todopago.

Ejemplo : https://developers.todopago.com.ar/formulario/commands?command=formulario&m=tffc4ec04-0903-7d8c-9d4a-391d23958ddf

**Comment by drarko** [comment]
Estimado,

El equipo de TodoPago se encuentra trabajando para resolver el inconveniente.
Notificaremos cuando el mismo se encuentre resuelto.

Gracias
